name: Continuous Integration

on:
  pull_request:
    branches: [ main ]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check prettier
        run: |
          npm install prettier --no-save prettier
          npx prettier --check '**/*.ts'
